In [1]:
#%pip install numpy

In [2]:
import numpy as np

## Basic Array Creation

In [3]:
#Always created using a list

arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
l=[1,2,3.67,4,"hello"]  #list
l

[1, 2, 3.67, 4, 'hello']

In [5]:
np.array(l)
#all data types will be changed to unicode - changed to strings!
#if all given and not strings - then all will be converted to floats!

array(['1', '2', '3.67', '4', 'hello'], dtype='<U32')

In [6]:
#Vectors and Matrics
# Vectors --> created in 1D space --> list =[1,2,3,4]
# Matrix --> Created in 2D (multi D) space (array given within an array)
#but list does not support multi list1

l=[[1,2,3], [4,5,6], [7,8,9]]
l
#gives 1D result looking only

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)
#will print Multi D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#Tensors - more than 2D

## Array Generation Function

In [9]:
arr=np.arange(1,11) #works like range function of loop
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr=np.zeros((6,6))
arr
#horizontal are rows
#vertical are columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
arr=np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
arr=np.ones((4,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
#linspace or linear spacing vs range func
#Return evenly spaced numbers over a specified interval.
arr = np.linspace(1,5,3)
#(linspace(start,stop,number of elements we want)) -- and it will provide equal spaces between
arr

array([1., 3., 5.])

## Random Generation Function

Random library - random integers 
add with numpy library - random array 
Also downloaded with numpy automatically
Random library - inbuilt

In [15]:
np.random.rand(5)
#np,random--libraries
#rand-->function
#produces vector --> all values between 0 and 1 --> concept of normalization!!

array([0.00121445, 0.88635546, 0.0345991 , 0.1835783 , 0.32257472])

In [16]:
np.random.randn(10)
#randn -> produces -3 to +3 --> concept of standardization

array([ 0.71966042, -0.19774797,  2.23555995,  1.99545018, -0.05834224,
       -0.37554708,  1.30970112,  0.27731408, -0.80898906,  1.35779278])

In [17]:
np.random.randint(6)
#gives between (0,6)
#output is a single digit

1

In [18]:
np.random.randint(10,20,10)
#Produces 10 element array between 10,20

array([18, 12, 18, 16, 13, 19, 10, 18, 17, 11], dtype=int32)

## Array Attributes

attributes are not called, func are called

In [19]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape #attribute no()

(3, 3)

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')

## Array Methods

In [23]:
min=arr.min()
print(min)
max=arr.max()
print(max)

1
9


In [24]:
summation=arr.sum()
print(summation)

45


In [25]:
np.sum(arr,axis=0)
#gives summation of columns = axis =0

array([12, 15, 18])

In [26]:
np.sum(arr,axis=1)
#gives row summation

array([ 6, 15, 24])

In [27]:
print(arr.mean())

5.0


In [28]:
arr.std() #gives standard deviation

np.float64(2.581988897471611)

In [29]:
arr.argmax() #gives max number ka index

np.int64(8)

In [30]:
arr.argmin() #gives min ka index

np.int64(0)

## Reshaping and Resizing

In [31]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
# above was 1D array or vector - let's reshape
# function reshape used here -- total element count should be present
arr=arr.reshape(6,5)
arr
# will give reshape(row,col)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr
# resizing done- assigned reshaped array to new 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])