## Indexing and Slicing of Vectors

In [1]:
import numpy as np

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### Indexing

In [8]:
int(arr[5]) #-->16 python integer

#while normally give numpy integer
# NumPy uses its own datatypes because they are:
# Faster
# Memory efficient
# Better for scientific computing

16

#### Slicing

In [11]:
arr[1:5] # [start:end]
arr[:5] # [from start to end point given]
arr[3::]  #from 3 till end index
arr[3::2] #from 3 skip 2 index and give output

array([14, 16, 18, 20])

## Numpy Indexing and Slicing of Matrix 

In [13]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0]

array([1, 2, 3, 4, 5])

In [16]:
arr[2]

array([11, 12, 13, 14, 15])

In [18]:
arr[4,3]
#element at 5th row and 4rd column
#indexing starts from 0

np.int64(24)

In [ ]:
arr[0:2,1:3]

#array([[2, 3],
    #    [7, 8]])


array([[2, 3],
       [7, 8]])

In [20]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
#selecting only col
#becomes a vector
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [39]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
#want odd only n remove even

Bool_index = arr % 2 !=0
Bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [41]:
arr=arr[Bool_index]
arr

array([11, 13, 15, 17, 19])

In [42]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#want even only
Bool_index = arr % 2 ==0
arr=arr[Bool_index]
arr

array([12, 14, 16, 18, 20])