In [2]:
import numpy as np

## Arithematic Operations

have to be same size

In [3]:
# similar number of values 
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [4]:
a1+a2
# unlike list where only appends and we have to loop

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1* a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

## Broadcasting


In [10]:
l=[10,20,30,40]
arr= np.array(l)

In [11]:
#l+ 10 --> gives error as not possible without looping 
arr+10

array([20, 30, 40, 50])

In [12]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr+10
#Broadcasting and Arithematic ops can be done on matrix as well

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### Arithmetic Operations in NumPy Arrays

Arithmetic operations happen between elements at the **same positions**.

Example:

```python
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
```

Output:

```python
[5 7 9]
```

Because:

```python
1+4
2+5
3+6
```

---

#### Broadcasting in NumPy

Broadcasting means NumPy automatically expands a smaller value/array to match the shape of a bigger array.

Example:

```python
a = np.array([1,2,3])

print(a + 10)
```

Output:

```python
[11 12 13]
```

Here NumPy “broadcasts” `10` like this internally:

```python
[10 10 10]
```

Then performs arithmetic.

---

#### Why Broadcasting is Different

Normal arithmetic operations:

* Need arrays of same size
* Element-by-element operation

Broadcasting:

* Allows different shapes/sizes
* NumPy automatically adjusts smaller data

Example:

```python
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])

print(a + b)
```

Output:

```python
[[11 12 13]
 [21 22 23]
 [31 32 33]]
```

NumPy automatically expanded shapes to make operation possible.

---

#### Short Definition

Broadcasting = Automatic expansion of smaller arrays/scalars so arithmetic operations can happen between different-sized arrays.


## Deep and Shallow Copy

works in list as well

In [18]:
a= np.arange(1,21)
a
#prints vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice= a[:5]
slice

array([1, 2, 3, 4, 5])

In [20]:
#broadcasting in slice
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a
#but a does not change -original is same! --> SHALLOW COPY
#It is not such in list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a=a[4:6]*10
a
#DEEP COPY - CHANGES ORIGINAL ARRAY


array([50, 60])

In [ ]:
b=a  #copied -- so changes in b will change a as well --> DEEP COPY
b[0]=999
b

array([999,  60])

In [26]:
a

array([999,  60])

In [ ]:
b=a.copy()
b[1]=888
print(b)
print(a)  #does not change as copy of a passed

[999 888]
[999  60]


## Matrix OPs

In [31]:
A= np.array(([1,2],[3,4]))
B= np.array(([5,6],[7,8]))

In [ ]:
print(A)
print(B)
print(A*B)  #multiples on basis of index
#but matrix does not multiply like this


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


In [ ]:
A @ B  #Matrix multiplication like in maths

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B)  # Also dot multiplication

array([[19, 22],
       [43, 50]])

In [36]:
#Transpose of array matrix
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


## Advance Array Manipulation 

### 1. Stacking of arrays

In [40]:
#You cannot stack 2 matrix 
#only stack vectors - 1D array

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
#Vertical stacking
np.vstack((a,b))   #-->takes tuple arguments

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
#Horizontal Stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Column Stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 2. Splitting Array

In [45]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#horizontal split -- but in equal parts - 3 given will give error
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
#Verical Split --> again in equal parts only
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
#np.vsplit(c,3) # will give error