## Valid Sudoku

Sudoku --

1. 9 - 3X3 blocks
2. Rows and col = 9,9
3. Whole row and col both sum = 45 (elements are 0 to 9)

In [37]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [38]:
# sum of each n every row 

s.sum()  #gives sum of whole sudoku

np.int64(405)

In [39]:
# rows sum is axis=1
b=np.sum(s, axis=1) 
#all 45 --> valid sudoku
b==45

for i in b:
    if i !=45:
        print("Sudoku invalid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [40]:
c=np.sum(s, axis=0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
#Let's check for each individual matrix==45 of block of 3 in 9 total blocks of 3X3

# h=np.hsplit(s,3)
# # sy=np.vsplit(s,2)
# h
# v=np.vsplit(h,3)

for i in range(0,9,3): # for rows
    for j in range(0,9,3): #for cols - step is imp
       n=(s[i:i+3,j:j+3])
       print(n.sum())  # all gives 45!!
      #  j=j+3
   #  i=i+3
   # range() does NOT care if you manually change the loop variable inside the loop.

45
45
45
45
45
45
45
45
45


**General Questions**

In [83]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [84]:
#Get the shape of the matrix.

data.shape # no brackets needed as shape is instance attribute

(5, 3)

In [85]:
#Find the average age of students.

#first col ka avg

meanVal=np.mean(data[0:5,0])
meanVal

np.float64(18.4)

In [86]:
#Extract Math marks of all students.

#extracting 1 col - 1st extracted all rows 0 to 5
data[0:5,1]

array([85, 92, 76, 65, 90])

In [87]:
#Find the highest Science mark.

marks=data[:,2]
np.max(marks)

np.int64(95)

In [88]:
#Get details of the student who scored more than 90 in Math.

#using boolean expression indexing

marks=data[:,1]
bool_exp= marks>90
data[bool_exp]
# array([[19, 92, 88]])

array([[19, 92, 88]])

In [89]:
#Increase Math marks of all students by 5.
marks=data[:,1:3]
marks+5  #array broadcasting -- cant be done in list

array([[ 90,  83],
       [ 97,  93],
       [ 81, 100],
       [ 70,  75],
       [ 95,  90]])

In [90]:
#Find how many students are younger than 19.

len(data[data[:, 0] <19])


3

In [91]:
#Calculate the average marks in each subject (column-wise mean).

print(data[:,1:])
np.mean(data[:,1:],axis=0)

[[85 78]
 [92 88]
 [76 95]
 [65 70]
 [90 85]]


array([81.6, 83.2])

In [93]:
#Get data of students who scored at least 80 in both subjects.

# 2 conditions - and operator can be used

data[(data[:,1] >=80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.

# q=data[:,2] <75
# r=data[q==True]=0
# r

data[data[:,2] < 75, 2] = 0
data
# data[condition, 2] = 0 → only Science column changes


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])